"""add api key to schema

Revision ID: 03c18dfaa4d8
Revises: b6832baa9b46
Create Date: 2025-05-15 11:46:45.182872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c18dfaa4d8'
down_revision: Union[str, None] = 'b6832baa9b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('api_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'checks', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checks', type_='unique')
    op.drop_column('checks', 'api_key')
    # ### end Alembic commands ###
