"""make check email fields optional

Revision ID: 5e3b5aa54900
Revises: 0045bda83b24
Create Date: 2025-05-29 12:27:16.992927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e3b5aa54900'
down_revision: Union[str, None] = '0045bda83b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checks', 'api_key',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checks', 'report_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checks', 'email_subject',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checks', 'email_body',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checks', 'email_body',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('checks', 'email_subject',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('checks', 'report_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('checks', 'api_key',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
