"""add report path to schema

Revision ID: ab7dcf506cc5
Revises: 03c18dfaa4d8
Create Date: 2025-05-20 09:47:24.215914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7dcf506cc5'
down_revision: Union[str, None] = '03c18dfaa4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('report_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'report_path')
    # ### end Alembic commands ###
