name: Build and Deploy to Staging

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'alma-item-checks'
  AZURE_FUNCTIONAPP_SLOT_NAME: 'stage'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Configure pip for private repository
      run: |
        echo "[global]
        extra-index-url = https://_:${{ secrets.AZURE_DEVOPS_PAT }}@pkgs.dev.azure.com/WRLCdev/Python/_packaging/wrlc-python/pypi/simple/" > ${{ runner.temp }}/pip.conf
        echo "PIP_CONFIG_FILE=${{ runner.temp }}/pip.conf" >> $GITHUB_ENV

    - name: Install project and all dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install . --target=".python_packages/lib/site-packages"

    - name: Archive deployment package
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          .
          # Exclude development files from the artifact to keep it clean
          !__pycache__/
          !.venv/
          !.vscode/
          !.idea/
          !.git*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Azure (stage)

    steps:
    - name: Download deployment package
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Function App Staging Slot'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: ${{ env.AZURE_FUNCTIONAPP_SLOT_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: false