name: Deploy Python Azure Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'your-function-app-name'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Azure (stage)

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup Python ${{ env.PYTHON_VERSION }} Environment'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Poetry'
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: 'Configure Poetry for Azure DevOps feed'
      run: |
        poetry config repositories.azure-devops https://pkgs.dev.azure.com/WRLCdev/Python/_packaging/wrlc-python/pypi/simple/
        poetry config http-basic.azure-devops build ${{ secrets.AZURE_DEVOPS_PAT }}

    - name: 'Load cached venv'
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: 'Install dependencies with Poetry'
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction

    - name: 'Add poetry export plugin'
      run: poetry self add poetry-plugin-export

    - name: 'Generate requirements.txt'
      run: |
        poetry export -f requirements.txt --output requirements.txt --without-hashes
        sed -i '/^--index-url/d' requirements.txt

    - name: 'Create deployment package'
      run: |
        rm -rf .venv/
        rm -rf .pytest_cache/
        rm -rf __pycache__/
        find . -type d -name "__pycache__" -delete
        find . -type f -name "*.pyc" -delete
        
        pip install -r requirements.txt --target .python_packages/lib/site-packages
      env:
        PIP_INDEX_URL: https://build:${{ secrets.AZURE_DEVOPS_PAT }}@pkgs.dev.azure.com/WRLCdev/Python/_packaging/wrlc-python/pypi/simple/
        PIP_TRUSTED_HOST: pkgs.dev.azure.com

    - name: 'Clear existing deployment files'
      run: |
        PUBLISH_PROFILE='${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'        
        SCM_URL=$(echo "$PUBLISH_PROFILE" | grep -oP 'publishUrl="\K[^"]*' | head -1)
        USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP 'userName="\K[^"]*' | head -1)
        PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP 'userPWD="\K[^"]*' | head -1)
        
        echo "Clearing /home/site/wwwroot contents..."
        
        ITEMS=$(curl -s "https://${SCM_URL}/api/vfs/site/wwwroot/" -u "${USERNAME}:${PASSWORD}" | jq -r '.[].name')
        
        for item in $ITEMS; do
          echo "Deleting: $item"
          curl -X DELETE "https://${SCM_URL}/api/vfs/site/wwwroot/$item" \
               -u "${USERNAME}:${PASSWORD}" \
               -H "If-Match: *"
        done
        
        echo "Cleared wwwroot directory"

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: false

    - name: 'Restart Function App'
      run: |
        # Extract publish profile details for API calls
        PUBLISH_PROFILE='${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
        
        # Extract SCM URL and credentials from publish profile
        SCM_URL=$(echo "$PUBLISH_PROFILE" | grep -oP 'publishUrl="\K[^"]*' | head -1)
        USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP 'userName="\K[^"]*' | head -1)
        PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP 'userPWD="\K[^"]*' | head -1)
        
        # Restart the SCM site to ensure file updates are reflected
        curl -X POST "https://${SCM_URL}/api/functions/host/restart" \
             -u "${USERNAME}:${PASSWORD}" \
             -H "Content-Type: application/json"
        
        sleep 10
        
        # Also restart the main function app
        curl -X POST "https://${USERNAME}:${PASSWORD}@${SCM_URL}/api/app/restart" \
             -H "Content-Type: application/json"