name: Deploy to Azure Function

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'alma-item-checks'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Azure (stage)

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Poetry'
      uses: snok/install-poetry@v1

    - name: 'Configure Poetry for Azure Artifacts'
      run: |
        poetry source add --priority=primary wrlc-python https://pkgs.dev.azure.com/WRLCdev/Python/_packaging/wrlc-python/pypi/simple/
        poetry config http-basic.wrlc-python __token__ ${{ secrets.AZURE_DEVOPS_PAT }}

    - name: "Install dependencies and package for Azure"
      run: |
        poetry install --without dev
        poetry run pip install --target="./.python_packages/lib/site-packages" .

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: false
