#file: noinspection UndefinedAction
name: Deploy to Azure Function

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'alma-item-checks'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install poetry export plugin
      run: poetry self add poetry-plugin-export

    - name: Export to requirements.txt
      run: poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: Configure pip for private feed
      run: |
        echo "[global]" > pip.conf
        echo "extra-index-url = https://${{ secrets.AZURE_ARTIFACTS_PAT }}@pkgs.dev.azure.com/your_organization_name/_packaging/your_feed_name/pypi/simple/" >> pip.conf

        mkdir -p ~/.pip/
        mv pip.conf ~/.pip/pip.conf
        
        echo "pip.conf configured successfully:"
        cat ~/.pip/pip.conf


    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
